name: Rust

on:
  push:
    branches: ["main", "ci/**"]
  pull_request:
    branches: ["main"]

env:
  CARGO_HOME: ${{ github.workspace }}/.cargohome
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        task: ["build", "test", "build:tls_compat_check"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
      - uses: jdx/mise-action@v2
      - run: mise run ${{ matrix.task }}
